version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    working_directory: ~/log-enricher
    steps:
      - checkout
      - run: python -m pip install --upgrade pip tox
      - run: tox
